version: '3.9'

services:
    postgres:
        image: postgres:17.0
        hostname: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./.data/db:/var/lib/postgresql/data
        env_file: "./.env"
