// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"orderbook-system/src/utils/database"
)

// Injectors from wire.go:

func InitializeDBConnection() (*database.DBConnection, error) {
	dbConnection, err := database.NewConnection()
	if err != nil {
		return nil, err
	}
	return dbConnection, nil
}
