// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"orderbook-system/src/modules/database"
	"orderbook-system/src/modules/users"
)

// Injectors from wire.go:

func InitializeDatabase() (*database.Database, error) {
	databaseDatabase, err := database.NewConnection()
	if err != nil {
		return nil, err
	}
	return databaseDatabase, nil
}

func InitializeUserModule(db *database.Database) (*users.Module, error) {
	module, err := users.NewUsersModule(db)
	if err != nil {
		return nil, err
	}
	return module, nil
}
